debian-install: put pagespeed-libraries.conf where it will be loaded
The way you used to install apache2 configuration on Debian-based systems
was to put it in /etc/apache2/conf.d/, but starting with Ubuntu 14 LTS
there's a new system where you install it to /etc/apache2/conf-available/ and
then run a2enconf to symlink it to /etc/apache2/conf-enabled.  On these
systems we weren't installing pagespeed-libraries.conf in a way that made
it usable, because when we put it in conf.d it just was never loaded.

Switch to installing to /etc/apache2/conf-available/, and then use a2enconf
if it's available.  If a2enconf isn't available, manually symlink to conf.d.

Fixes: https://github.com/pagespeed/mod_pagespeed/issues/1389

diff --git a/install/debian/postinst b/install/debian/postinst
--- a/install/debian/postinst
+++ b/install/debian/postinst
@@ -19,6 +19,26 @@ case "$1" in
 
         test ! -e /etc/apache2/mods-enabled/pagespeed.load && \
             a2enmod pagespeed
+
+        # Enable pagespeed-libraries.conf.  On recent systems you install config
+        # files into /etc/apache2/conf-available and then use a2enconf to
+        # symlink it into /etc/apache2/conf-enabled.  On older systems there's
+        # just /etc/apache2/conf.d/, so we manually symlink it there instead.
+        # See https://github.com/pagespeed/mod_pagespeed/issues/1389
+        if hash a2enconf 2> /dev/null; then
+          # a2enconf is available; use it.
+          a2enconf pagespeed_libraries
+        elif [ -d /etc/apache2/conf.d/ ]; then
+          # this ubuntu is too old for that; manually symlink it
+          if [ -e /etc/apache2/conf.d/pagespeed_libraries.conf ]; then
+            echo "Not symlinking on top of existing pagespeed_libraries.conf"
+          else
+            ln -s ../conf-available/pagespeed_libraries.conf \
+                  /etc/apache2/conf.d/
+          fi
+        else
+          echo "failed to configure pagespeed_libraries.conf" >&2
+        fi
     ;;
     abort-upgrade|abort-remove|abort-deconfigure)
     ;;
